### ISSUE TITLE
Entering memo without spaces causes send window text to go out of bounds

### ISSUE THREAD

**Issue by rex4539** [adityapk00/zecwallet-electron#22]
It's actually the window after you press "Send" whose text goes out of bounds.

<img width="1598" alt="Screen Shot 2020-02-03 at 22 31 15" src="https://user-images.githubusercontent.com/227442/73688573-fffcf380-46d4-11ea-8939-f43afb2964a9.png">

**Comment by adityapk00** [comment]
Oh, the confirm screen. Sorry, I misunderstood.
