### ISSUE TITLE
Apostrophe not rendered properly in memo

### ISSUE THREAD

**Issue by rex4539** [adityapk00/zecwallet-electron#24]
<img width="232" alt="Screen Shot 2020-02-04 at 00 03 35" src="https://user-images.githubusercontent.com/227442/73695022-ef9f4580-46e1-11ea-9529-acd9e00f581f.png">
<img width="252" alt="Screen Shot 2020-02-04 at 00 03 46" src="https://user-images.githubusercontent.com/227442/73695029-f29a3600-46e1-11ea-9043-e44ded522630.png">

**Comment by adityapk00** [comment]
Fixed in 884b3ea
