### ISSUE TITLE
UI not updated after sending transaction without internet

### ISSUE THREAD

**Issue by rex4539** [adityapk00/zecwallet-electron#26]
Steps:
1. Disconnect from internet.
2. Send a transaction.
3. Reconnect to internet.

What happened:
The transaction never appears in dashboard and the `zcashd` page stops updating.

Expected result:
When the transaction is confirmed, it should appear in dashboard. `zcashd` page is constantly updated.

Notes:
When the app is restarted, then the transaction appears and the `zcashd` page updates again, so it's a refresh issue. zecwallet-qt handles this scenario very well.

**Comment by adityapk00** [comment]
I think this was fixed with one of the refresh bug fixes
