### ISSUE TITLE
Splash screen icon shouldn't be draggable

### ISSUE THREAD

**Issue by rex4539** [adityapk00/zecwallet-electron#9]
https://www.dropbox.com/s/275qqfxyz5farry/Bug.mov?dl=0

**Comment by adityapk00** [comment]
Just curious - Are you starting the app with `yarn dev` or `yarn start`?

**Comment by rex4539** [comment]
`yarn start`

**Comment by adityapk00** [comment]
Cool... Just FYI... If you start with `yarn dev`, the console window will open up where you can see additional debug info
